version: "2.27"

services:
  postgres:
    image: postgres:12-alpine
    container_name: ${DB_DOCKER_CONTAINER_NAME}
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: ${REDIS_DOCKER_CONTAINER_NAME}
    ports:
      - 6379:6379

volumes:
  db_data: