services:
  postgres:
    image: pgvector/pgvector:latest
    container_name: ${DB_DOCKER_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql  # Mount backup file
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    networks:
      - aggregator_network

  redis:
    image: redis:latest
    container_name: aggregator_redis
    networks:
      - aggregator_network
    ports:
      - 6379:6379

volumes:
  postgres_data:

networks:
  aggregator_network:
    external: true
